name: podtimer
description: "Track Spotify podcast listening."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  routerino: ^0.8.0

  flutter_localizations:
   sdk: flutter
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  crypto: ^3.0.7
  http: ^1.6.0
  url_launcher: ^6.3.2
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
